apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-multitool
  namespace: nginx-space
spec:
  selector:
    matchLabels:
      app: ng-mt
  replicas: 1
  template:
    metadata:
      labels:
        app: ng-mt
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-index
              mountPath: /usr/share/nginx/html/
      - name: multitool
        image: wbitt/network-multitool
        ports:
        - containerPort: 8080
        env:
          - name: HTTP_PORT
            valueFrom:
              configMapKeyRef:
                name: mt-maps
                key: HTTP_PORT
      volumes:
      - name: nginx-index
        configMap:
          name: mt-maps
